# Generated by Django 5.0.1 on 2024-10-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='generos',
            field=models.ManyToManyField(db_table='TB_LIBROS_GENEROS', related_name='libros', to='api.genero'),
        ),
        migrations.DeleteModel(
            name='LibroGenero',
        ),
    ]
