# Generated by Django 5.0.1 on 2024-10-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_usuario_rol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialvisualizacion',
            options={'ordering': ['-fecha_visualizacion']},
        ),
        migrations.AlterUniqueTogether(
            name='historialvisualizacion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='historialvisualizacion',
            name='tipo_accion',
            field=models.CharField(blank=True, choices=[('LECTURA', 'Lectura'), ('DESCARGA', 'Descarga')], max_length=10, null=True),
        ),
    ]
