# Generated by Django 5.0.1 on 2024-10-29 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_historialvisualizacion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialvisualizacion',
            options={'ordering': ['-HistorialFechaVisualizacion']},
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='contenido',
            new_name='ComentariosContenido',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='fecha_creacion',
            new_name='ComentariosFechaCreacion',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='libro',
            new_name='ComentariosLibro',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='usuario',
            new_name='ComentariosUsuario',
        ),
        migrations.RenameField(
            model_name='favorito',
            old_name='fecha_agregado',
            new_name='FavoritosFechaAgregado',
        ),
        migrations.RenameField(
            model_name='favorito',
            old_name='libro',
            new_name='FavoritosLibro',
        ),
        migrations.RenameField(
            model_name='favorito',
            old_name='usuario',
            new_name='FavoritosUsuario',
        ),
        migrations.RenameField(
            model_name='genero',
            old_name='nombre',
            new_name='GenerosNombre',
        ),
        migrations.RenameField(
            model_name='historialvisualizacion',
            old_name='fecha_visualizacion',
            new_name='HistorialFechaVisualizacion',
        ),
        migrations.RenameField(
            model_name='historialvisualizacion',
            old_name='libro',
            new_name='HistorialLibro',
        ),
        migrations.RenameField(
            model_name='historialvisualizacion',
            old_name='tipo_accion',
            new_name='HistorialTipoAccion',
        ),
        migrations.RenameField(
            model_name='historialvisualizacion',
            old_name='usuario',
            new_name='HistorialUsuario',
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='url_archivo',
            new_name='LibrosArchivo',
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='autor',
            new_name='LibrosAutor',
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='descripcion',
            new_name='LibrosDescripcion',
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='fecha_publicacion',
            new_name='LibrosFechaPublicacion',
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='fecha_subida',
            new_name='LibrosFechaSubida',
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='generos',
            new_name='LibrosGeneros',
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='isbn',
            new_name='LibrosISBN',
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='portada',
            new_name='LibrosPortada',
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='titulo',
            new_name='LibrosTitulo',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='fecha_registro',
            new_name='UsuariosFechaRegistro',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='imagen_perfil',
            new_name='UsuariosImagenPerfil',
        ),
        migrations.AlterUniqueTogether(
            name='favorito',
            unique_together={('FavoritosUsuario', 'FavoritosLibro')},
        ),
    ]
