# Generated by Django 5.0.1 on 2024-10-29 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_historialvisualizacion_options_and_more'),
    ]

    operations = [
    ]
