# Generated by Django 5.0.1 on 2024-10-29 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_create_default_genres'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialvisualizacion',
            options={'ordering': ['-fecha_visualizacion']},
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='ComentariosContenido',
            new_name='contenido',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='ComentariosFechaCreacion',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='ComentariosLibro',
            new_name='libro',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='ComentariosUsuario',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='favorito',
            old_name='FavoritosFechaAgregado',
            new_name='fecha_agregado',
        ),
        migrations.RenameField(
            model_name='favorito',
            old_name='FavoritosLibro',
            new_name='libro',
        ),
        migrations.RenameField(
            model_name='favorito',
            old_name='FavoritosUsuario',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='genero',
            old_name='GenerosNombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='historialvisualizacion',
            old_name='HistorialFechaVisualizacion',
            new_name='fecha_visualizacion',
        ),
        migrations.RenameField(
            model_name='historialvisualizacion',
            old_name='HistorialLibro',
            new_name='libro',
        ),
        migrations.RenameField(
            model_name='historialvisualizacion',
            old_name='HistorialTipoAccion',
            new_name='tipo_accion',
        ),
        migrations.RenameField(
            model_name='historialvisualizacion',
            old_name='HistorialUsuario',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='LibrosAutor',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='LibrosDescripcion',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='LibrosFechaPublicacion',
            new_name='fecha_publicacion',
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='LibrosFechaSubida',
            new_name='fecha_subida',
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='LibrosGeneros',
            new_name='generos',
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='LibrosISBN',
            new_name='isbn',
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='LibrosPortada',
            new_name='portada',
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='LibrosTitulo',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='LibrosArchivo',
            new_name='url_archivo',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='UsuariosFechaRegistro',
            new_name='fecha_registro',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='UsuariosImagenPerfil',
            new_name='imagen_perfil',
        ),
        migrations.AlterUniqueTogether(
            name='favorito',
            unique_together={('usuario', 'libro')},
        ),
    ]
