# Generated by Django 5.0.1 on 2024-10-29 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_historialvisualizacion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='contenido',
            field=models.TextField(db_column='ComentarioContenido'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, db_column='ComentarioFechaCreacion'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='libro',
            field=models.ForeignKey(db_column='ComentarioIdLibro', on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='api.libro'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(db_column='ComentarioIdUsuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favorito',
            name='fecha_agregado',
            field=models.DateTimeField(auto_now_add=True, db_column='FavoritoFechaAgregado'),
        ),
        migrations.AlterField(
            model_name='favorito',
            name='libro',
            field=models.ForeignKey(db_column='FavoritoIdLibro', on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='api.libro'),
        ),
        migrations.AlterField(
            model_name='favorito',
            name='usuario',
            field=models.ForeignKey(db_column='FavoritoIdUsuario', on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='genero',
            name='nombre',
            field=models.CharField(db_column='GeneroNombre', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='historialvisualizacion',
            name='fecha_visualizacion',
            field=models.DateTimeField(auto_now_add=True, db_column='HistorialFechaVisualizacion'),
        ),
        migrations.AlterField(
            model_name='historialvisualizacion',
            name='libro',
            field=models.ForeignKey(db_column='HistorialIdLibro', on_delete=django.db.models.deletion.CASCADE, to='api.libro'),
        ),
        migrations.AlterField(
            model_name='historialvisualizacion',
            name='tipo_accion',
            field=models.CharField(blank=True, choices=[('LECTURA', 'Lectura'), ('DESCARGA', 'Descarga')], db_column='HistorialTipoAccion', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historialvisualizacion',
            name='usuario',
            field=models.ForeignKey(db_column='HistorialIdUsuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.CharField(db_column='LibroAutor', max_length=100),
        ),
        migrations.AlterField(
            model_name='libro',
            name='descripcion',
            field=models.TextField(db_column='LibroDescripcion'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='fecha_publicacion',
            field=models.DateField(db_column='LibroFechaPublicacion'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='fecha_subida',
            field=models.DateTimeField(auto_now_add=True, db_column='LibroFechaSubida'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='isbn',
            field=models.CharField(db_column='LibroISBN', max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='portada',
            field=models.ImageField(blank=True, db_column='LibroPortada', null=True, upload_to='libros/portadas/'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(db_column='LibroTitulo', max_length=200),
        ),
        migrations.AlterField(
            model_name='libro',
            name='url_archivo',
            field=models.FileField(blank=True, db_column='LibroArchivo', null=True, upload_to='libros/pdfs/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, db_column='UsuarioFechaRegistro'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='imagen_perfil',
            field=models.ImageField(blank=True, db_column='UsuarioImagenPerfil', null=True, upload_to='perfiles/'),
        ),
    ]
